/* The following code was generated by JFlex 1.6.1 */

package compi;
import static compi.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>D:/RepoVR/ProyectoCompi/Compi/src/compi/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\10\1\11\1\11\1\10\22\0\1\6\1\55\1\15"+
    "\1\16\1\0\1\51\1\56\1\13\1\62\1\63\1\12\1\47\1\70"+
    "\1\50\1\3\1\7\1\75\7\4\2\2\1\73\1\71\1\53\1\52"+
    "\1\54\1\72\1\0\4\5\1\101\1\100\5\1\1\77\10\1\1\76"+
    "\5\1\1\64\1\14\1\65\1\61\1\74\1\0\1\27\1\30\1\32"+
    "\1\17\1\20\1\21\1\40\1\34\1\22\1\1\1\31\1\37\1\42"+
    "\1\23\1\35\1\46\1\1\1\25\1\33\1\26\1\36\1\41\1\24"+
    "\1\43\1\45\1\44\1\66\1\57\1\67\1\60\6\0\1\11\u1fa2\0"+
    "\1\11\1\11\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\3\1\20\2\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\4\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\1\1\3\2\0\1\32"+
    "\1\33\1\32\1\33\1\0\1\5\1\0\1\34\1\35"+
    "\1\0\1\36\3\0\1\37\1\0\1\2\1\40\5\2"+
    "\1\41\22\2\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\0\1\55\1\56"+
    "\1\0\1\57\1\60\1\57\2\0\5\2\1\61\1\2"+
    "\1\3\27\2\1\62\1\63\1\62\1\63\1\64\1\55"+
    "\1\65\1\66\1\67\1\5\1\0\2\2\1\70\1\71"+
    "\5\2\1\72\3\2\1\73\1\74\12\2\1\75\1\76"+
    "\1\2\1\77\1\100\1\101\1\100\1\102\1\103\1\102"+
    "\1\103\2\0\2\2\1\104\1\105\3\2\1\106\1\2"+
    "\1\107\4\2\1\110\1\2\1\111\1\112\1\0\1\113"+
    "\1\112\1\55\1\0\1\2\1\114\2\2\1\115\1\116"+
    "\1\55\1\117\1\120\2\2\1\121";

  private static int [] zzUnpackAction() {
    int [] result = new int[229];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\102\0\204\0\306\0\u0108\0\u014a\0\u018c\0\u01ce"+
    "\0\u0210\0\u0252\0\u0294\0\u02d6\0\u0318\0\u035a\0\u039c\0\u03de"+
    "\0\u0420\0\u0462\0\u04a4\0\u04e6\0\u0528\0\u056a\0\u05ac\0\u05ee"+
    "\0\u0630\0\u0672\0\u06b4\0\u06f6\0\u0738\0\u077a\0\u07bc\0\u07fe"+
    "\0\u0840\0\u0882\0\u08c4\0\u0906\0\102\0\u077a\0\102\0\102"+
    "\0\102\0\102\0\102\0\102\0\102\0\102\0\102\0\102"+
    "\0\204\0\u0948\0\u098a\0\u09cc\0\u0a0e\0\u0a50\0\u0a92\0\u0ad4"+
    "\0\u0b16\0\u0b58\0\u0b9a\0\102\0\102\0\u0210\0\102\0\u0bdc"+
    "\0\u0252\0\u0c1e\0\102\0\u0c60\0\u0ca2\0\u0ce4\0\u0d26\0\u0d68"+
    "\0\u0daa\0\u0dec\0\u0e2e\0\204\0\u0e70\0\u0eb2\0\u0ef4\0\u0f36"+
    "\0\u0f78\0\u0fba\0\u0ffc\0\u103e\0\u1080\0\u10c2\0\u1104\0\u1146"+
    "\0\u1188\0\u11ca\0\u120c\0\u124e\0\u1290\0\u12d2\0\102\0\102"+
    "\0\102\0\102\0\102\0\102\0\102\0\102\0\102\0\102"+
    "\0\u1314\0\u1356\0\u1398\0\u13da\0\u13da\0\u141c\0\102\0\u145e"+
    "\0\u14a0\0\u14e2\0\u1524\0\u1566\0\u15a8\0\u15ea\0\u162c\0\204"+
    "\0\u166e\0\204\0\u16b0\0\u16f2\0\u1734\0\u1776\0\u17b8\0\u17fa"+
    "\0\u183c\0\u187e\0\u18c0\0\u1902\0\u1944\0\u1986\0\u19c8\0\u1a0a"+
    "\0\u1a4c\0\u1a8e\0\u1ad0\0\u1b12\0\u1b54\0\u1b96\0\u1bd8\0\u1c1a"+
    "\0\u1c5c\0\u1c9e\0\u1ce0\0\u1d22\0\u1d64\0\u1da6\0\u1de8\0\102"+
    "\0\102\0\102\0\u0b9a\0\u1e2a\0\u1e6c\0\u1eae\0\204\0\204"+
    "\0\u1ef0\0\u1f32\0\u1f74\0\u1fb6\0\u1ff8\0\204\0\u203a\0\u207c"+
    "\0\u20be\0\204\0\204\0\u2100\0\u2142\0\u2184\0\u21c6\0\u2208"+
    "\0\u224a\0\u228c\0\u22ce\0\u2310\0\u2352\0\204\0\204\0\u2394"+
    "\0\204\0\u23d6\0\102\0\u2418\0\u245a\0\u249c\0\u24de\0\u2520"+
    "\0\u2562\0\u25a4\0\u25e6\0\u2628\0\204\0\204\0\u266a\0\u26ac"+
    "\0\u26ee\0\204\0\u2730\0\204\0\u2772\0\u27b4\0\u27f6\0\u2838"+
    "\0\204\0\u287a\0\102\0\102\0\u28bc\0\102\0\u28bc\0\u28fe"+
    "\0\u2940\0\u2982\0\204\0\u29c4\0\u2a06\0\204\0\102\0\u2a48"+
    "\0\102\0\204\0\u2a8a\0\u2acc\0\204";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[229];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\4\1\3\1\6\1\7"+
    "\1\6\1\0\1\10\1\11\1\2\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\3\1\20\1\21\1\22\1\23"+
    "\1\24\1\3\1\25\1\26\2\3\1\27\1\30\1\31"+
    "\1\32\1\33\4\3\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\4\3\103\0\2\3\1\0\2\3\11\0"+
    "\30\3\25\0\6\3\2\0\1\4\1\63\1\4\13\0"+
    "\1\64\15\0\1\65\1\66\35\0\1\4\1\67\1\70"+
    "\1\0\1\64\2\0\1\71\1\0\1\71\70\0\1\71"+
    "\12\0\1\6\1\0\1\6\100\0\1\72\2\0\1\73"+
    "\37\0\1\74\101\0\1\75\27\0\13\76\1\77\1\100"+
    "\65\76\14\101\1\102\1\103\64\101\17\0\1\104\63\0"+
    "\2\3\1\0\2\3\11\0\1\3\1\105\14\3\1\106"+
    "\11\3\25\0\6\3\1\0\2\3\1\0\2\3\11\0"+
    "\4\3\1\107\13\3\1\110\3\3\1\111\3\3\25\0"+
    "\6\3\1\0\2\3\1\0\2\3\11\0\16\3\1\112"+
    "\1\3\1\113\7\3\25\0\6\3\1\0\2\3\1\0"+
    "\2\3\11\0\2\3\1\114\1\3\1\115\23\3\25\0"+
    "\6\3\1\0\2\3\1\0\2\3\11\0\6\3\1\116"+
    "\6\3\1\117\12\3\25\0\6\3\1\0\2\3\1\0"+
    "\2\3\11\0\1\3\1\120\26\3\25\0\6\3\1\0"+
    "\2\3\1\0\2\3\11\0\26\3\1\121\1\3\25\0"+
    "\6\3\1\0\2\3\1\0\2\3\11\0\17\3\1\122"+
    "\10\3\25\0\6\3\1\0\2\3\1\0\2\3\11\0"+
    "\6\3\1\123\21\3\25\0\6\3\1\0\2\3\1\0"+
    "\2\3\11\0\10\3\1\124\4\3\1\125\1\126\11\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\3\3"+
    "\1\127\1\3\1\130\1\3\1\131\5\3\1\132\12\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\4\3"+
    "\1\133\23\3\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\16\3\1\134\11\3\25\0\6\3\1\0\2\3"+
    "\1\0\2\3\11\0\16\3\1\122\11\3\25\0\6\3"+
    "\1\0\2\3\1\0\2\3\11\0\16\3\1\135\11\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\10\3"+
    "\1\136\17\3\25\0\6\3\47\0\1\137\2\0\1\140"+
    "\77\0\1\141\1\0\1\142\1\0\1\45\77\0\1\45"+
    "\101\0\1\143\101\0\1\144\1\46\100\0\1\145\1\0"+
    "\1\46\77\0\1\146\101\0\1\45\3\0\1\147\75\0"+
    "\1\45\4\0\1\150\24\0\1\4\1\63\1\151\13\0"+
    "\1\64\15\0\1\65\1\66\3\0\1\152\31\0\1\151"+
    "\1\67\1\70\1\0\1\64\2\0\1\153\1\0\1\153"+
    "\70\0\1\153\6\0\1\154\1\0\1\154\43\0\1\155"+
    "\24\0\1\154\43\0\1\156\101\0\1\157\141\0\1\160"+
    "\101\0\1\157\4\0\1\71\1\0\1\71\13\0\1\64"+
    "\54\0\1\71\3\0\1\64\10\72\2\0\70\72\12\73"+
    "\1\161\67\73\10\76\2\0\70\76\10\101\2\0\70\101"+
    "\20\0\1\162\62\0\2\3\1\0\2\3\11\0\2\3"+
    "\1\163\25\3\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\17\3\1\164\10\3\25\0\6\3\1\0\2\3"+
    "\1\0\2\3\11\0\17\3\1\165\10\3\25\0\6\3"+
    "\1\0\2\3\1\0\2\3\11\0\14\3\1\166\13\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\7\3"+
    "\1\167\20\3\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\6\3\1\170\21\3\25\0\6\3\1\0\2\3"+
    "\1\0\2\3\11\0\16\3\1\171\11\3\25\0\6\3"+
    "\1\0\2\3\1\0\2\3\11\0\7\3\1\172\20\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\3\3"+
    "\1\173\24\3\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\3\3\1\174\24\3\25\0\6\3\1\0\2\3"+
    "\1\0\2\3\11\0\7\3\1\175\1\176\10\3\1\177"+
    "\6\3\25\0\6\3\1\0\2\3\1\0\2\3\11\0"+
    "\27\3\1\200\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\7\3\1\201\20\3\25\0\6\3\1\0\2\3"+
    "\1\0\2\3\11\0\1\3\1\202\26\3\25\0\6\3"+
    "\1\0\2\3\1\0\2\3\11\0\14\3\1\203\13\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\10\3"+
    "\1\204\17\3\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\4\3\1\205\23\3\25\0\6\3\1\0\2\3"+
    "\1\0\2\3\11\0\21\3\1\206\3\3\1\207\2\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\3\3"+
    "\1\210\24\3\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\6\3\1\211\1\3\1\212\17\3\25\0\6\3"+
    "\1\0\2\3\1\0\2\3\11\0\16\3\1\213\11\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\3\3"+
    "\1\214\10\3\1\215\13\3\25\0\6\3\1\0\2\3"+
    "\1\0\2\3\11\0\4\3\1\216\23\3\25\0\6\3"+
    "\1\0\2\3\1\0\2\3\11\0\3\3\1\217\14\3"+
    "\1\220\7\3\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\3\3\1\221\24\3\25\0\6\3\2\0\1\4"+
    "\1\63\1\151\13\0\1\64\15\0\1\222\1\223\35\0"+
    "\1\151\1\224\1\225\1\0\1\64\2\0\1\226\1\0"+
    "\2\226\11\0\3\226\5\0\2\226\1\0\1\226\42\0"+
    "\1\226\2\0\2\226\2\0\1\227\1\0\1\227\13\0"+
    "\1\64\1\230\15\0\1\231\35\0\1\227\1\0\1\231"+
    "\1\230\1\64\2\0\1\154\1\0\1\154\70\0\1\154"+
    "\43\0\1\232\141\0\1\232\2\0\7\73\1\233\2\73"+
    "\1\161\67\73\21\0\1\234\61\0\2\3\1\0\2\3"+
    "\11\0\10\3\1\235\17\3\25\0\6\3\1\0\2\3"+
    "\1\0\2\3\11\0\11\3\1\236\16\3\25\0\6\3"+
    "\1\0\2\3\1\0\2\3\11\0\23\3\1\237\4\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\1\3"+
    "\1\240\26\3\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\1\3\1\241\26\3\25\0\6\3\1\0\2\3"+
    "\1\0\2\3\11\0\10\3\1\242\17\3\25\0\6\3"+
    "\1\0\2\3\1\0\2\3\11\0\7\3\1\243\20\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\20\3"+
    "\1\244\7\3\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\17\3\1\245\10\3\25\0\6\3\1\0\2\3"+
    "\1\0\2\3\11\0\1\246\27\3\25\0\6\3\1\0"+
    "\2\3\1\0\2\3\11\0\3\3\1\247\24\3\25\0"+
    "\6\3\1\0\2\3\1\0\2\3\11\0\1\3\1\250"+
    "\26\3\25\0\6\3\1\0\2\3\1\0\2\3\11\0"+
    "\16\3\1\237\11\3\25\0\6\3\1\0\2\3\1\0"+
    "\2\3\11\0\10\3\1\251\17\3\25\0\6\3\1\0"+
    "\2\3\1\0\2\3\11\0\1\3\1\252\26\3\25\0"+
    "\6\3\1\0\2\3\1\0\2\3\11\0\6\3\1\253"+
    "\21\3\25\0\6\3\1\0\2\3\1\0\2\3\11\0"+
    "\7\3\1\254\4\3\1\255\13\3\25\0\6\3\1\0"+
    "\2\3\1\0\2\3\11\0\4\3\1\256\23\3\25\0"+
    "\6\3\1\0\2\3\1\0\2\3\11\0\1\3\1\257"+
    "\26\3\25\0\6\3\1\0\2\3\1\0\2\3\11\0"+
    "\7\3\1\260\20\3\25\0\6\3\1\0\2\3\1\0"+
    "\2\3\11\0\17\3\1\261\10\3\25\0\6\3\1\0"+
    "\2\3\1\0\2\3\11\0\7\3\1\262\20\3\25\0"+
    "\6\3\1\0\2\3\1\0\2\3\11\0\6\3\1\263"+
    "\21\3\25\0\6\3\1\0\2\3\1\0\2\3\11\0"+
    "\16\3\1\264\11\3\25\0\6\3\1\0\2\3\1\0"+
    "\2\3\11\0\3\3\1\265\24\3\25\0\6\3\1\0"+
    "\2\3\1\0\2\3\11\0\21\3\1\266\6\3\25\0"+
    "\6\3\1\0\2\3\1\0\2\3\11\0\1\267\27\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\10\3"+
    "\1\270\17\3\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\4\3\1\271\23\3\25\0\6\3\37\0\1\272"+
    "\101\0\1\273\141\0\1\274\101\0\1\273\4\0\1\226"+
    "\1\0\2\226\11\0\3\226\5\0\2\226\1\0\1\226"+
    "\3\0\1\275\1\276\35\0\1\226\1\277\1\300\2\226"+
    "\2\0\1\227\1\301\1\227\13\0\1\64\1\230\15\0"+
    "\1\231\35\0\1\227\1\0\1\231\1\230\1\64\22\0"+
    "\1\302\60\0\2\3\1\0\2\3\11\0\17\3\1\303"+
    "\10\3\25\0\6\3\1\0\2\3\1\0\2\3\11\0"+
    "\20\3\1\304\7\3\25\0\6\3\1\0\2\3\1\0"+
    "\2\3\11\0\6\3\1\264\21\3\25\0\6\3\1\0"+
    "\2\3\1\0\2\3\11\0\7\3\1\237\20\3\25\0"+
    "\6\3\1\0\2\3\1\0\2\3\11\0\1\3\1\305"+
    "\26\3\25\0\6\3\1\0\2\3\1\0\2\3\11\0"+
    "\1\3\1\306\26\3\25\0\6\3\1\0\2\3\1\0"+
    "\2\3\11\0\6\3\1\307\21\3\25\0\6\3\1\0"+
    "\2\3\1\0\2\3\11\0\14\3\1\310\13\3\25\0"+
    "\6\3\1\0\2\3\1\0\2\3\11\0\1\311\27\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\12\3"+
    "\1\312\15\3\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\3\3\1\313\24\3\25\0\6\3\1\0\2\3"+
    "\1\0\2\3\11\0\7\3\1\314\20\3\25\0\6\3"+
    "\1\0\2\3\1\0\2\3\11\0\1\3\1\315\26\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\16\3"+
    "\1\316\11\3\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\13\3\1\317\14\3\25\0\6\3\1\0\2\3"+
    "\1\0\2\3\11\0\13\3\1\242\14\3\25\0\6\3"+
    "\1\0\2\3\1\0\2\3\11\0\3\3\1\320\24\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\7\3"+
    "\1\321\20\3\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\4\3\1\237\23\3\25\0\6\3\1\0\2\3"+
    "\1\0\2\3\11\0\21\3\1\206\6\3\25\0\6\3"+
    "\1\0\2\3\1\0\2\3\11\0\7\3\1\322\20\3"+
    "\25\0\6\3\37\0\1\323\141\0\1\323\41\0\1\324"+
    "\37\0\1\325\41\0\1\326\141\0\1\327\101\0\1\326"+
    "\4\0\1\330\1\0\1\330\70\0\1\330\27\0\1\331"+
    "\57\0\2\3\1\0\2\3\11\0\20\3\1\332\7\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\1\3"+
    "\1\237\26\3\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\4\3\1\333\23\3\25\0\6\3\1\0\2\3"+
    "\1\0\2\3\11\0\7\3\1\334\20\3\25\0\6\3"+
    "\1\0\2\3\1\0\2\3\11\0\1\3\1\316\26\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\4\3"+
    "\1\335\23\3\25\0\6\3\1\0\2\3\1\0\2\3"+
    "\11\0\1\237\27\3\25\0\6\3\1\0\2\3\1\0"+
    "\2\3\11\0\2\3\1\237\25\3\25\0\6\3\1\0"+
    "\2\3\1\0\2\3\11\0\15\3\1\336\12\3\25\0"+
    "\6\3\1\0\2\3\1\0\2\3\11\0\13\3\1\237"+
    "\14\3\25\0\6\3\1\0\2\3\1\0\2\3\11\0"+
    "\3\3\1\236\24\3\25\0\6\3\77\0\1\337\4\0"+
    "\1\340\1\0\1\340\14\0\1\230\15\0\1\231\35\0"+
    "\1\340\1\0\1\231\1\230\21\0\1\341\62\0\2\3"+
    "\1\0\2\3\11\0\7\3\1\342\20\3\25\0\6\3"+
    "\1\0\2\3\1\0\2\3\11\0\1\3\1\343\26\3"+
    "\25\0\6\3\1\0\2\3\1\0\2\3\11\0\17\3"+
    "\1\344\10\3\25\0\6\3\2\0\1\340\1\301\1\340"+
    "\14\0\1\230\15\0\1\231\35\0\1\340\1\0\1\231"+
    "\1\230\2\0\2\3\1\0\2\3\11\0\6\3\1\237"+
    "\21\3\25\0\6\3\1\0\2\3\1\0\2\3\11\0"+
    "\1\3\1\345\26\3\25\0\6\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11022];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\42\1\1\11\1\1\12\11\2\1\2\0"+
    "\4\1\1\0\1\1\1\0\2\11\1\0\1\11\3\0"+
    "\1\11\1\0\32\1\12\11\1\1\1\0\2\1\1\0"+
    "\1\1\1\11\1\1\2\0\45\1\3\11\1\1\1\0"+
    "\36\1\1\11\5\1\2\0\20\1\2\11\1\0\1\11"+
    "\2\1\1\0\5\1\1\11\1\1\1\11\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[229];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public int GetLine() { return yyline + 1; }
    // ...

    public String lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 198) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme=yytext(); return ERROR;
            }
          case 82: break;
          case 2: 
            { lexeme=yytext(); return Identificador;
            }
          case 83: break;
          case 3: 
            { lexeme=yytext(); return Int;
            }
          case 84: break;
          case 4: 
            { lexeme=yytext(); return Punto;
            }
          case 85: break;
          case 5: 
            { /*Ignore*/
            }
          case 86: break;
          case 6: 
            { lexeme=yytext(); return OperadorDiv;
            }
          case 87: break;
          case 7: 
            { lexeme=yytext(); return OperadorMulti;
            }
          case 88: break;
          case 8: 
            { lexeme=yytext(); return OperadorSuma;
            }
          case 89: break;
          case 9: 
            { lexeme=yytext(); return OperadorResta;
            }
          case 90: break;
          case 10: 
            { lexeme=yytext(); return OperadorMod;
            }
          case 91: break;
          case 11: 
            { lexeme=yytext(); return OperadorAsignacion;
            }
          case 92: break;
          case 12: 
            { lexeme=yytext(); return OperadorMenor;
            }
          case 93: break;
          case 13: 
            { lexeme=yytext(); return OperadorMayor;
            }
          case 94: break;
          case 14: 
            { lexeme=yytext(); return OperadorNegacion;
            }
          case 95: break;
          case 15: 
            { lexeme=yytext(); return Operador;
            }
          case 96: break;
          case 16: 
            { lexeme=yytext(); return ParentesisA;
            }
          case 97: break;
          case 17: 
            { lexeme=yytext(); return ParentesisC;
            }
          case 98: break;
          case 18: 
            { lexeme=yytext(); return ParentesisCuadradoA;
            }
          case 99: break;
          case 19: 
            { lexeme=yytext(); return ParentesisCuadradoC;
            }
          case 100: break;
          case 20: 
            { lexeme=yytext(); return LlaveA;
            }
          case 101: break;
          case 21: 
            { lexeme=yytext(); return LlaveC;
            }
          case 102: break;
          case 22: 
            { lexeme=yytext(); return Coma;
            }
          case 103: break;
          case 23: 
            { lexeme=yytext(); return PuntoComa;
            }
          case 104: break;
          case 24: 
            { lexeme=yytext(); return Interrogacion;
            }
          case 105: break;
          case 25: 
            { lexeme=yytext(); return DosPuntos;
            }
          case 106: break;
          case 26: 
            { lexeme=yytext(); return IntU;
            }
          case 107: break;
          case 27: 
            { lexeme=yytext(); return IntL;
            }
          case 108: break;
          case 28: 
            { lexeme=yytext(); return OperadorAsignacionDiv;
            }
          case 109: break;
          case 29: 
            { lexeme=yytext(); return OperadorAsignacionMul;
            }
          case 110: break;
          case 30: 
            { lexeme=yytext(); return LiteralChar;
            }
          case 111: break;
          case 31: 
            { lexeme=yytext(); return LiteralString;
            }
          case 112: break;
          case 32: 
            { lexeme=yytext(); return Do;
            }
          case 113: break;
          case 33: 
            { lexeme=yytext(); return If;
            }
          case 114: break;
          case 34: 
            { lexeme=yytext(); return OperadorIncremento;
            }
          case 115: break;
          case 35: 
            { lexeme=yytext(); return OperadorAsignacionSuma;
            }
          case 116: break;
          case 36: 
            { lexeme=yytext(); return OperadorDecremento;
            }
          case 117: break;
          case 37: 
            { lexeme=yytext(); return OperadorAsignacionResta;
            }
          case 118: break;
          case 38: 
            { lexeme=yytext(); return OperadorComparacion;
            }
          case 119: break;
          case 39: 
            { lexeme=yytext(); return OperadorMenorIgual;
            }
          case 120: break;
          case 40: 
            { lexeme=yytext(); return OperadorMayorIgual;
            }
          case 121: break;
          case 41: 
            { lexeme=yytext(); return OperadorDiferencia;
            }
          case 122: break;
          case 42: 
            { lexeme=yytext(); return OperadorAnd;
            }
          case 123: break;
          case 43: 
            { lexeme=yytext(); return OperadorOr;
            }
          case 124: break;
          case 44: 
            { lexeme=yytext(); return Octal;
            }
          case 125: break;
          case 45: 
            { lexeme=yytext(); return Double;
            }
          case 126: break;
          case 46: 
            { lexeme=yytext(); return PuntoFlotante;
            }
          case 127: break;
          case 47: 
            { lexeme=yytext(); return IntUL;
            }
          case 128: break;
          case 48: 
            { lexeme=yytext(); return IntLL;
            }
          case 129: break;
          case 49: 
            { lexeme=yytext(); return For;
            }
          case 130: break;
          case 50: 
            { lexeme=yytext(); return OctalU;
            }
          case 131: break;
          case 51: 
            { lexeme=yytext(); return OctalL;
            }
          case 132: break;
          case 52: 
            { lexeme=yytext(); return Hexadecimal;
            }
          case 133: break;
          case 53: 
            { lexeme=yytext(); return Float;
            }
          case 134: break;
          case 54: 
            { lexeme=yytext(); return DoubleL;
            }
          case 135: break;
          case 55: 
            { lexeme=yytext(); return IntULL;
            }
          case 136: break;
          case 56: 
            { lexeme=yytext(); return Reservada;
            }
          case 137: break;
          case 57: 
            { lexeme=yytext(); return Else;
            }
          case 138: break;
          case 58: 
            { lexeme=yytext(); return Read;
            }
          case 139: break;
          case 59: 
            { lexeme=yytext(); return Case;
            }
          case 140: break;
          case 60: 
            { lexeme=yytext(); return Char;
            }
          case 141: break;
          case 61: 
            { lexeme=yytext(); return Long;
            }
          case 142: break;
          case 62: 
            { lexeme=yytext(); return Void;
            }
          case 143: break;
          case 63: 
            { lexeme=yytext(); return Main;
            }
          case 144: break;
          case 64: 
            { lexeme=yytext(); return OctalUL;
            }
          case 145: break;
          case 65: 
            { lexeme=yytext(); return OctalLL;
            }
          case 146: break;
          case 66: 
            { lexeme=yytext(); return HexadecimalU;
            }
          case 147: break;
          case 67: 
            { lexeme=yytext(); return HexadecimalL;
            }
          case 148: break;
          case 68: 
            { lexeme=yytext(); return Write;
            }
          case 149: break;
          case 69: 
            { lexeme=yytext(); return While;
            }
          case 150: break;
          case 70: 
            { lexeme=yytext(); return Break;
            }
          case 151: break;
          case 71: 
            { lexeme=yytext(); return Const;
            }
          case 152: break;
          case 72: 
            { lexeme=yytext(); return Short;
            }
          case 153: break;
          case 73: 
            { lexeme=yytext(); return OctalULL;
            }
          case 154: break;
          case 74: 
            { lexeme=yytext(); return HexadecimalUL;
            }
          case 155: break;
          case 75: 
            { lexeme=yytext(); return HexadecimalLL;
            }
          case 156: break;
          case 76: 
            { lexeme=yytext(); return Return;
            }
          case 157: break;
          case 77: 
            { lexeme=yytext(); return Switch;
            }
          case 158: break;
          case 78: 
            { lexeme=yytext(); return HexadecimalULL;
            }
          case 159: break;
          case 79: 
            { lexeme=yytext(); return Define;
            }
          case 160: break;
          case 80: 
            { lexeme=yytext(); return Default;
            }
          case 161: break;
          case 81: 
            { lexeme=yytext(); return Continue;
            }
          case 162: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
