/* The following code was generated by JFlex 1.6.1 */

package compi;

import static compi.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>D:/NetBeansProjects/Compi/src/compi/lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\10\1\11\1\11\1\10\22\0\1\6\1\53\1\14"+
    "\2\0\1\53\1\55\1\13\1\45\1\45\1\12\1\46\1\6\1\47"+
    "\1\3\1\7\1\57\7\4\2\2\1\45\1\45\1\52\1\50\1\51"+
    "\1\45\1\0\4\5\1\63\1\62\5\1\1\61\10\1\1\60\5\1"+
    "\1\45\1\0\1\45\1\53\1\56\1\0\1\15\1\21\1\25\1\32"+
    "\1\23\1\33\1\37\1\27\1\31\1\1\1\24\1\34\1\35\1\30"+
    "\1\20\1\43\1\1\1\22\1\26\1\17\1\16\1\44\1\41\1\36"+
    "\1\42\1\40\1\45\1\54\1\45\1\45\6\0\1\11\u1fa2\0\1\11"+
    "\1\11\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\2\4\2\1"+
    "\17\2\7\4\1\1\1\3\1\0\1\6\1\0\1\7"+
    "\1\6\1\7\1\0\1\5\2\0\1\10\1\0\1\10"+
    "\17\2\2\11\6\2\1\12\1\0\1\13\1\14\1\15"+
    "\1\0\1\16\1\14\1\0\30\2\1\17\1\20\1\17"+
    "\1\20\1\21\1\13\1\22\1\23\1\24\1\5\16\2"+
    "\1\25\1\26\1\25\1\27\1\30\1\27\1\30\1\0"+
    "\7\2\1\31\1\32\1\0\1\33\1\32\1\13\2\2"+
    "\1\34\1\13";

  private static int [] zzUnpackAction() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\u0138\0\u016c"+
    "\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4\0\u02d8\0\u030c"+
    "\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444\0\u0478\0\u04ac"+
    "\0\u04e0\0\64\0\u0514\0\u0548\0\u057c\0\u05b0\0\u05e4\0\u0618"+
    "\0\150\0\u064c\0\u0680\0\u06b4\0\u06e8\0\u071c\0\u0750\0\u0784"+
    "\0\u07b8\0\u07ec\0\u0820\0\u01a0\0\u01a0\0\u01d4\0\u01d4\0\u0854"+
    "\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958\0\u098c\0\u09c0\0\u09f4"+
    "\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\150\0\u0b60"+
    "\0\u0b94\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0ccc\0\u0d00"+
    "\0\u0d34\0\u0d68\0\u0d9c\0\u0d9c\0\64\0\u0dd0\0\u0e04\0\u0e38"+
    "\0\u0e6c\0\u0ea0\0\u0ed4\0\u0f08\0\u0f3c\0\u0f70\0\u0fa4\0\u0fd8"+
    "\0\u100c\0\u1040\0\u1074\0\u10a8\0\u10dc\0\u1110\0\u1144\0\u1178"+
    "\0\u11ac\0\u11e0\0\u1214\0\u1248\0\u127c\0\u12b0\0\u12e4\0\u1318"+
    "\0\u134c\0\u1380\0\u13b4\0\u13e8\0\u141c\0\64\0\64\0\64"+
    "\0\u0820\0\u1450\0\u1484\0\u14b8\0\u14ec\0\u1520\0\u1554\0\u1588"+
    "\0\u15bc\0\u15f0\0\u1624\0\u1658\0\u168c\0\u16c0\0\u16f4\0\u1728"+
    "\0\64\0\u175c\0\u1790\0\u17c4\0\u17f8\0\u182c\0\u1860\0\u1894"+
    "\0\u18c8\0\u18fc\0\u1930\0\u1964\0\u1998\0\u19cc\0\64\0\64"+
    "\0\u1a00\0\64\0\u1a00\0\u1a34\0\u1a68\0\u1a9c\0\64\0\u1ad0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\4\1\3\1\6\1\7"+
    "\1\6\1\0\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\3\1\16\1\17\1\20\1\3\1\21\1\22\2\3"+
    "\1\23\1\24\1\25\1\26\2\3\1\27\1\3\1\30"+
    "\2\3\1\31\1\32\1\33\1\34\1\10\1\35\1\36"+
    "\1\10\1\37\1\40\1\41\1\42\4\3\65\0\2\3"+
    "\1\0\2\3\7\0\30\3\11\0\6\3\2\0\1\4"+
    "\1\43\1\4\11\0\1\44\4\0\1\45\10\0\1\46"+
    "\22\0\1\4\1\47\1\50\1\0\1\45\2\0\1\51"+
    "\1\0\1\51\52\0\1\51\12\0\1\6\1\0\1\6"+
    "\62\0\1\52\2\0\1\53\35\0\1\32\63\0\1\32"+
    "\13\0\10\54\2\0\1\54\1\55\50\54\10\56\2\0"+
    "\2\56\1\57\47\56\1\0\2\3\1\0\2\3\7\0"+
    "\1\3\1\60\26\3\11\0\6\3\1\0\2\3\1\0"+
    "\2\3\7\0\13\3\1\61\14\3\11\0\6\3\1\0"+
    "\2\3\1\0\2\3\7\0\25\3\1\62\2\3\11\0"+
    "\6\3\1\0\2\3\1\0\2\3\7\0\5\3\1\63"+
    "\22\3\11\0\6\3\1\0\2\3\1\0\2\3\7\0"+
    "\6\3\1\64\21\3\11\0\6\3\1\0\2\3\1\0"+
    "\2\3\7\0\13\3\1\65\3\3\1\66\1\3\1\67"+
    "\6\3\11\0\6\3\1\0\2\3\1\0\2\3\7\0"+
    "\1\66\2\3\1\70\6\3\1\71\15\3\11\0\6\3"+
    "\1\0\2\3\1\0\2\3\7\0\2\3\1\72\7\3"+
    "\1\73\1\3\1\74\7\3\1\75\3\3\11\0\6\3"+
    "\1\0\2\3\1\0\2\3\7\0\13\3\1\76\2\3"+
    "\1\77\11\3\11\0\6\3\1\0\2\3\1\0\2\3"+
    "\7\0\3\3\1\100\2\3\1\101\21\3\11\0\6\3"+
    "\1\0\2\3\1\0\2\3\7\0\3\3\1\102\13\3"+
    "\1\103\10\3\11\0\6\3\1\0\2\3\1\0\2\3"+
    "\7\0\3\3\1\104\24\3\11\0\6\3\1\0\2\3"+
    "\1\0\2\3\7\0\3\3\1\60\24\3\11\0\6\3"+
    "\1\0\2\3\1\0\2\3\7\0\12\3\1\105\15\3"+
    "\11\0\6\3\1\0\2\3\1\0\2\3\7\0\3\3"+
    "\1\106\24\3\11\0\6\3\46\0\1\32\1\0\1\32"+
    "\62\0\3\32\62\0\1\32\1\10\62\0\1\32\1\0"+
    "\1\10\61\0\1\32\3\0\1\32\57\0\1\32\4\0"+
    "\1\32\10\0\1\4\1\43\1\107\11\0\1\44\4\0"+
    "\1\45\10\0\1\46\1\0\1\110\20\0\1\107\1\47"+
    "\1\50\1\0\1\45\2\0\1\111\1\0\1\111\52\0"+
    "\1\111\40\0\1\112\31\0\1\113\1\0\1\113\42\0"+
    "\1\114\7\0\1\113\40\0\1\115\110\0\1\116\63\0"+
    "\1\115\4\0\1\51\1\0\1\51\16\0\1\45\33\0"+
    "\1\51\3\0\1\45\10\52\2\0\52\52\12\53\1\117"+
    "\51\53\1\0\2\3\1\0\2\3\7\0\2\3\1\120"+
    "\25\3\11\0\6\3\1\0\2\3\1\0\2\3\7\0"+
    "\11\3\1\121\2\3\1\122\13\3\11\0\6\3\1\0"+
    "\2\3\1\0\2\3\7\0\26\3\1\123\1\3\11\0"+
    "\6\3\1\0\2\3\1\0\2\3\7\0\6\3\1\124"+
    "\21\3\11\0\6\3\1\0\2\3\1\0\2\3\7\0"+
    "\2\3\1\125\17\3\1\126\5\3\11\0\6\3\1\0"+
    "\2\3\1\0\2\3\7\0\1\3\1\127\26\3\11\0"+
    "\6\3\1\0\2\3\1\0\2\3\7\0\11\3\1\130"+
    "\16\3\11\0\6\3\1\0\2\3\1\0\2\3\7\0"+
    "\2\3\1\131\25\3\11\0\6\3\1\0\2\3\1\0"+
    "\2\3\7\0\13\3\1\132\14\3\11\0\6\3\1\0"+
    "\2\3\1\0\2\3\7\0\1\102\27\3\11\0\6\3"+
    "\1\0\2\3\1\0\2\3\7\0\1\133\4\3\1\134"+
    "\22\3\11\0\6\3\1\0\2\3\1\0\2\3\7\0"+
    "\3\3\1\135\24\3\11\0\6\3\1\0\2\3\1\0"+
    "\2\3\7\0\22\3\1\136\1\137\4\3\11\0\6\3"+
    "\1\0\2\3\1\0\2\3\7\0\14\3\1\140\13\3"+
    "\11\0\6\3\1\0\2\3\1\0\2\3\7\0\2\3"+
    "\1\77\25\3\11\0\6\3\1\0\2\3\1\0\2\3"+
    "\7\0\1\3\1\141\26\3\11\0\6\3\1\0\2\3"+
    "\1\0\2\3\7\0\16\3\1\142\11\3\11\0\6\3"+
    "\1\0\2\3\1\0\2\3\7\0\5\3\1\77\22\3"+
    "\11\0\6\3\1\0\2\3\1\0\2\3\7\0\3\3"+
    "\1\143\24\3\11\0\6\3\1\0\2\3\1\0\2\3"+
    "\7\0\13\3\1\144\14\3\11\0\6\3\1\0\2\3"+
    "\1\0\2\3\7\0\14\3\1\145\13\3\11\0\6\3"+
    "\1\0\2\3\1\0\2\3\7\0\14\3\1\146\2\3"+
    "\1\147\10\3\11\0\6\3\2\0\1\4\1\43\1\107"+
    "\11\0\1\150\4\0\1\45\10\0\1\151\22\0\1\107"+
    "\1\152\1\153\1\0\1\45\2\0\1\154\1\0\2\154"+
    "\7\0\1\154\3\0\1\154\1\0\1\154\1\0\1\154"+
    "\4\0\2\154\23\0\1\154\2\0\2\154\2\0\1\155"+
    "\1\0\1\155\16\0\1\45\7\0\1\156\1\157\22\0"+
    "\1\155\1\0\1\157\1\156\1\45\34\0\1\160\31\0"+
    "\1\113\1\0\1\113\52\0\1\113\65\0\1\160\2\0"+
    "\7\53\1\161\2\53\1\117\51\53\1\0\2\3\1\0"+
    "\2\3\7\0\3\3\1\77\24\3\11\0\6\3\1\0"+
    "\2\3\1\0\2\3\7\0\14\3\1\162\13\3\11\0"+
    "\6\3\1\0\2\3\1\0\2\3\7\0\3\3\1\163"+
    "\24\3\11\0\6\3\1\0\2\3\1\0\2\3\7\0"+
    "\6\3\1\164\21\3\11\0\6\3\1\0\2\3\1\0"+
    "\2\3\7\0\1\165\27\3\11\0\6\3\1\0\2\3"+
    "\1\0\2\3\7\0\1\3\1\166\26\3\11\0\6\3"+
    "\1\0\2\3\1\0\2\3\7\0\14\3\1\167\13\3"+
    "\11\0\6\3\1\0\2\3\1\0\2\3\7\0\20\3"+
    "\1\77\7\3\11\0\6\3\1\0\2\3\1\0\2\3"+
    "\7\0\6\3\1\77\21\3\11\0\6\3\1\0\2\3"+
    "\1\0\2\3\7\0\6\3\1\166\21\3\11\0\6\3"+
    "\1\0\2\3\1\0\2\3\7\0\2\3\1\170\6\3"+
    "\1\76\16\3\11\0\6\3\1\0\2\3\1\0\2\3"+
    "\7\0\2\3\1\171\25\3\11\0\6\3\1\0\2\3"+
    "\1\0\2\3\7\0\1\3\1\172\26\3\11\0\6\3"+
    "\1\0\2\3\1\0\2\3\7\0\5\3\1\76\22\3"+
    "\11\0\6\3\1\0\2\3\1\0\2\3\7\0\13\3"+
    "\1\173\14\3\11\0\6\3\1\0\2\3\1\0\2\3"+
    "\7\0\6\3\1\174\21\3\11\0\6\3\1\0\2\3"+
    "\1\0\2\3\7\0\2\3\1\175\25\3\11\0\6\3"+
    "\1\0\2\3\1\0\2\3\7\0\4\3\1\145\23\3"+
    "\11\0\6\3\1\0\2\3\1\0\2\3\7\0\1\176"+
    "\27\3\11\0\6\3\1\0\2\3\1\0\2\3\7\0"+
    "\1\76\27\3\11\0\6\3\1\0\2\3\1\0\2\3"+
    "\7\0\22\3\1\77\5\3\11\0\6\3\1\0\2\3"+
    "\1\0\2\3\7\0\17\3\1\130\10\3\11\0\6\3"+
    "\1\0\2\3\1\0\2\3\7\0\15\3\1\77\12\3"+
    "\11\0\6\3\1\0\2\3\1\0\2\3\7\0\1\177"+
    "\27\3\11\0\6\3\34\0\1\200\63\0\1\201\110\0"+
    "\1\202\63\0\1\201\4\0\1\154\1\0\2\154\7\0"+
    "\1\154\1\203\2\0\1\154\1\0\1\154\1\0\1\154"+
    "\4\0\2\154\1\204\22\0\1\154\1\205\1\206\2\154"+
    "\2\0\1\155\1\207\1\155\16\0\1\45\7\0\1\156"+
    "\1\157\22\0\1\155\1\0\1\157\1\156\1\45\1\0"+
    "\2\3\1\0\2\3\7\0\22\3\1\136\5\3\11\0"+
    "\6\3\1\0\2\3\1\0\2\3\7\0\13\3\1\77"+
    "\14\3\11\0\6\3\1\0\2\3\1\0\2\3\7\0"+
    "\15\3\1\210\12\3\11\0\6\3\1\0\2\3\1\0"+
    "\2\3\7\0\7\3\1\77\20\3\11\0\6\3\1\0"+
    "\2\3\1\0\2\3\7\0\5\3\1\163\22\3\11\0"+
    "\6\3\1\0\2\3\1\0\2\3\7\0\11\3\1\211"+
    "\16\3\11\0\6\3\1\0\2\3\1\0\2\3\7\0"+
    "\14\3\1\212\13\3\11\0\6\3\1\0\2\3\1\0"+
    "\2\3\7\0\14\3\1\213\13\3\11\0\6\3\1\0"+
    "\2\3\1\0\2\3\7\0\10\3\1\76\17\3\11\0"+
    "\6\3\1\0\2\3\1\0\2\3\7\0\6\3\1\146"+
    "\21\3\11\0\6\3\1\0\2\3\1\0\2\3\7\0"+
    "\3\3\1\214\24\3\11\0\6\3\1\0\2\3\1\0"+
    "\2\3\7\0\10\3\1\215\17\3\11\0\6\3\1\0"+
    "\2\3\1\0\2\3\7\0\1\3\1\216\26\3\11\0"+
    "\6\3\1\0\2\3\1\0\2\3\7\0\2\3\1\105"+
    "\25\3\11\0\6\3\34\0\1\217\110\0\1\217\36\0"+
    "\1\220\24\0\1\221\36\0\1\222\110\0\1\223\63\0"+
    "\1\222\4\0\1\224\1\0\1\224\52\0\1\224\5\0"+
    "\2\3\1\0\2\3\7\0\6\3\1\214\21\3\11\0"+
    "\6\3\1\0\2\3\1\0\2\3\7\0\2\3\1\225"+
    "\25\3\11\0\6\3\1\0\2\3\1\0\2\3\7\0"+
    "\13\3\1\226\14\3\11\0\6\3\1\0\2\3\1\0"+
    "\2\3\7\0\10\3\1\77\17\3\11\0\6\3\1\0"+
    "\2\3\1\0\2\3\7\0\16\3\1\77\11\3\11\0"+
    "\6\3\1\0\2\3\1\0\2\3\7\0\12\3\1\77"+
    "\15\3\11\0\6\3\1\0\2\3\1\0\2\3\7\0"+
    "\17\3\1\76\10\3\11\0\6\3\61\0\1\227\4\0"+
    "\1\230\1\0\1\230\26\0\1\156\1\157\22\0\1\230"+
    "\1\0\1\157\1\156\2\0\2\3\1\0\2\3\7\0"+
    "\6\3\1\102\21\3\11\0\6\3\1\0\2\3\1\0"+
    "\2\3\7\0\1\3\1\130\26\3\11\0\6\3\2\0"+
    "\1\230\1\207\1\230\26\0\1\156\1\157\22\0\1\230"+
    "\1\0\1\157\1\156\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6916];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\27\1\1\11\10\1\1\0\1\1\1\0"+
    "\3\1\1\0\1\1\2\0\1\1\1\0\31\1\1\0"+
    "\3\1\1\0\1\11\1\1\1\0\36\1\3\11\20\1"+
    "\1\11\5\1\1\0\7\1\2\11\1\0\1\11\4\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 196) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme=yytext(); return ERROR;
            }
          case 29: break;
          case 2: 
            { lexeme=yytext(); return Identificador;
            }
          case 30: break;
          case 3: 
            { lexeme=yytext(); return Int;
            }
          case 31: break;
          case 4: 
            { lexeme=yytext(); return Operador;
            }
          case 32: break;
          case 5: 
            { /*Ignore*/
            }
          case 33: break;
          case 6: 
            { lexeme=yytext(); return IntU;
            }
          case 34: break;
          case 7: 
            { lexeme=yytext(); return IntL;
            }
          case 35: break;
          case 8: 
            { lexeme=yytext(); return Literal;
            }
          case 36: break;
          case 9: 
            { lexeme=yytext(); return Reservada;
            }
          case 37: break;
          case 10: 
            { lexeme=yytext(); return Octal;
            }
          case 38: break;
          case 11: 
            { lexeme=yytext(); return Double;
            }
          case 39: break;
          case 12: 
            { lexeme=yytext(); return IntUL;
            }
          case 40: break;
          case 13: 
            { lexeme=yytext(); return PuntoFlotante;
            }
          case 41: break;
          case 14: 
            { lexeme=yytext(); return IntLL;
            }
          case 42: break;
          case 15: 
            { lexeme=yytext(); return OctalU;
            }
          case 43: break;
          case 16: 
            { lexeme=yytext(); return OctalL;
            }
          case 44: break;
          case 17: 
            { lexeme=yytext(); return Hexadecimal;
            }
          case 45: break;
          case 18: 
            { lexeme=yytext(); return Float;
            }
          case 46: break;
          case 19: 
            { lexeme=yytext(); return DoubleL;
            }
          case 47: break;
          case 20: 
            { lexeme=yytext(); return IntULL;
            }
          case 48: break;
          case 21: 
            { lexeme=yytext(); return OctalUL;
            }
          case 49: break;
          case 22: 
            { lexeme=yytext(); return OctalLL;
            }
          case 50: break;
          case 23: 
            { lexeme=yytext(); return HexadecimalU;
            }
          case 51: break;
          case 24: 
            { lexeme=yytext(); return HexadecimalL;
            }
          case 52: break;
          case 25: 
            { lexeme=yytext(); return OctalULL;
            }
          case 53: break;
          case 26: 
            { lexeme=yytext(); return HexadecimalUL;
            }
          case 54: break;
          case 27: 
            { lexeme=yytext(); return HexadecimalLL;
            }
          case 55: break;
          case 28: 
            { lexeme=yytext(); return HexadecimalULL;
            }
          case 56: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
