
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 28 21:34:41 CST 2022
//----------------------------------------------------

package compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OperadorAsignacionMul = 29;
  public static final int PuntoComa = 48;
  public static final int Coma = 47;
  public static final int OperadorMayor = 36;
  public static final int If = 14;
  public static final int Void = 20;
  public static final int LlaveC = 46;
  public static final int OperadorIncremento = 32;
  public static final int LlaveA = 45;
  public static final int Define = 2;
  public static final int Default = 10;
  public static final int Else = 12;
  public static final int OperadorMulti = 24;
  public static final int Read = 4;
  public static final int Break = 5;
  public static final int OperadorDecremento = 33;
  public static final int Long = 16;
  public static final int OperadorOr = 42;
  public static final int Return = 17;
  public static final int OperadorAsignacion = 31;
  public static final int While = 21;
  public static final int Int = 50;
  public static final int OperadorComparacion = 34;
  public static final int For = 13;
  public static final int EOF = 0;
  public static final int DosPuntos = 49;
  public static final int OperadorAnd = 41;
  public static final int error = 1;
  public static final int Switch = 19;
  public static final int OperadorResta = 23;
  public static final int Integer = 15;
  public static final int OperadorNegacion = 40;
  public static final int OperadorDiv = 25;
  public static final int Char = 7;
  public static final int ERROR = 53;
  public static final int Do = 11;
  public static final int Continue = 9;
  public static final int Case = 6;
  public static final int Short = 18;
  public static final int LiteralChar = 52;
  public static final int Const = 8;
  public static final int OperadorAsignacionResta = 28;
  public static final int OperadorMod = 26;
  public static final int Identificador = 51;
  public static final int OperadorDiferencia = 39;
  public static final int OperadorMenorIgual = 38;
  public static final int ParentesisC = 44;
  public static final int OperadorSuma = 22;
  public static final int OperadorAsignacionSuma = 27;
  public static final int OperadorAsignacionDiv = 30;
  public static final int ParentesisA = 43;
  public static final int Write = 3;
  public static final int OperadorMayorIgual = 37;
  public static final int OperadorMenor = 35;
}

